project_name: gocoop

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: linux-arm
    binary: gocoop-linux-{{ .Arch }}
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
    no_unique_dist_dir: true

  - id: linux-arm64
    binary: gocoop-linux-{{ .Arch }}
    main: ./main.go
    goos:
      - linux
    goarch:
      - arm
      - arm64
    no_unique_dist_dir: true